print('Bom dia')
print('Olá Mundo!')
print('Boa tarde')
print('Oh Neymar')
print('Boa noite')
print('Jair Bolsonaro')
print('Boa madrugada')
print('Luiz Inacio Lula da Silva')
print('Boa tempestade')
print('Fim da escala 6x1')